apiVersion: v1
kind: Namespace
metadata:
  name: gitea-runner
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runner-data
  namespace: gitea-runner
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-runner
  namespace: gitea-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-runner
  template:
    metadata:
      labels:
        app: gitea-runner
    spec:
      containers:
      - name: runner
        image: gitea/act_runner:latest
        env:
        - name: GITEA_INSTANCE_URL
          value: "http://gitea.gitea.svc.cluster.local:3000"
        - name: GITEA_RUNNER_REGISTRATION_TOKEN
          value: "QrND4GkbypZcFcnAzHy7NsRsiEo5AoPHbHgQRx8i"
        - name: GITEA_RUNNER_NAME
          value: "k3s-runner-01"
        - name: GITEA_RUNNER_LABELS
          value: "ubuntu-latest:docker://ubuntu:22.04,ubuntu-22.04:docker://ubuntu:22.04"
        - name: DOCKER_HOST
          value: "tcp://localhost:2375"
        - name: HTTP_PROXY
          value: "http://100.79.69.118:10808"
        - name: HTTPS_PROXY
          value: "http://100.79.69.118:10808"
        - name: NO_PROXY
          value: "localhost,127.0.0.1,10.0.0.0/8,100.101.0.0/16,192.168.0.0/16,gitea.gitea.svc.cluster.local"
        volumeMounts:
        - name: runner-data
          mountPath: /data
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: "1"
            memory: 1Gi

      - name: dind
        image: docker:24-dind
        securityContext:
          privileged: true
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        - name: HTTP_PROXY
          value: "http://100.79.69.118:10808"
        - name: HTTPS_PROXY
          value: "http://100.79.69.118:10808"
        - name: NO_PROXY
          value: "localhost,127.0.0.1,10.0.0.0/8,100.101.0.0/16,192.168.0.0/16"
        args:
        - dockerd
        - --host=tcp://0.0.0.0:2375
        - --host=unix:///var/run/docker.sock
        volumeMounts:
        - name: runner-data
          mountPath: /data
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: "1"
            memory: 1Gi

      volumes:
      - name: runner-data
        persistentVolumeClaim:
          claimName: runner-data
